package:
  name: halign4
  version: "2.0.0"

source:
  git_url: https://github.com/pinglu-zhang/HAlign-4.git
  # git_rev: v2.0.0

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

  host:
    - zlib
    - libcurl
    - llvm-openmp
    - sysroot_linux-64 2.17

  run:
    - zlib
    - libcurl
    - llvm-openmp
    - mafft
    - minipoa
    - clustalo

test:
  commands:
    - halign4 -h
    - mafft --version
    - minipoa -h
    - clustalo --version

about:
  home: https://github.com/pinglu-zhang/HAlign-4
  license: MIT
  summary: "HAlign-4"
  description: "HAlign 4: A New Strategy for Rapidly Aligning Millions of Sequences"
  channels:
    - malab
    - bioconda
    - conda-forge
    - defaults
