package:
  name: halign4
  version: "2.0.0"

source:
  git_url: https://github.com/pinglu-zhang/HAlign-4.git
  # 建议固定 tag/commit，保证可复现
  # git_rev: v2.0.0

build:
  number: 0
  script: bash build.sh

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - zlib
    - libcurl
    - llvm-openmp  # 给 find_package(OpenMP) 提供 runtime/headers（Linux 下很稳）
    - sysroot_linux-64 2.17
  run:
    - zlib
    - libcurl
    - llvm-openmp

test:
  commands:
    - halign4 -h

about:
  home: https://github.com/pinglu-zhang/HAlign-4
  license: MIT
  summary: "HAlign-4"
  description: "HAlign 4: A New Strategy for Rapidly Aligning Millions of Sequences"
